# Generated by Django 5.2.7 on 2026-02-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'корзину', 'verbose_name_plural': 'Корзина'},
        ),
    ]
