# Generated by Django 5.2.7 on 2025-10-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
