# Generated by Django 5.2.7 on 2025-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_categories_category_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='goods_category',
        ),
    ]
