# Generated by Django 5.2.7 on 2025-10-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
