# Generated by Django 5.2.7 on 2026-02-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_category_options_alter_product_options'),
        ('orders', '0002_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product', verbose_name='Товар'),
        ),
    ]
